"""creating PROJECTS table

Revision ID: 0ebf4f1b6dd3
Revises: 783116a29bae
Create Date: 2022-10-17 16:33:04.678560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ebf4f1b6dd3"
down_revision = "783116a29bae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("county", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=False),
        sa.Column("project_desc", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("start_budget", sa.Text(), nullable=False),
        sa.Column("end_budget", sa.Text(), nullable=True),
        sa.Column("lot_num", sa.String(length=3), nullable=True),
        sa.Column("lockbx_code", sa.String(length=4), nullable=True),
        sa.Column("dumpster_drop", sa.Text(), nullable=True),
        sa.Column("portajohn_srv_day", sa.Text(), nullable=True),
        sa.Column("manager_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["managers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects")
    # ### end Alembic commands ###
