"""creating MANAGERS table

Revision ID: 783116a29bae
Revises: 7e4ebc355854
Create Date: 2022-10-15 16:45:40.503393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "783116a29bae"
down_revision = "7e4ebc355854"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(length=12), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("managers")
    # ### end Alembic commands ###
